package com.blog.utils;

import com.blog.config.JwtProperties;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Pure unit test for {@link JwtTokenProvider}. No Spring context, no DB,
 * no Docker - just verifies that tokens generated by the provider can be
 * round-tripped through it and that signatures from a different key are
 * rejected.
 */
class JwtTokenProviderTest {

    private JwtTokenProvider provider;

    @BeforeEach
    void setUp() {
        provider = newProvider("this-is-a-test-secret-key-that-is-at-least-32-bytes");
    }

    @Test
    void generated_token_round_trips_username_and_role() {
        String token = provider.generateToken("alice", "ADMIN");

        assertThat(provider.isTokenValid(token)).isTrue();
        assertThat(provider.parseUsername(token)).isEqualTo("alice");
        assertThat(provider.parseRole(token)).isEqualTo("ADMIN");
    }

    @Test
    void garbage_input_is_rejected_without_throwing() {
        assertThat(provider.isTokenValid("")).isFalse();
        assertThat(provider.isTokenValid("not.a.real.token")).isFalse();
        assertThat(provider.isTokenValid("a.b.c.d.e")).isFalse();
    }

    @Test
    void token_signed_with_a_different_key_is_rejected() {
        JwtTokenProvider attacker = newProvider("a-completely-different-secret-key-that-is-32-bytes");
        String forged = attacker.generateToken("bob", "ADMIN");

        assertThat(provider.isTokenValid(forged)).isFalse();
    }

    private JwtTokenProvider newProvider(String secret) {
        JwtProperties properties = new JwtProperties();
        properties.setSecret(secret);
        properties.setExpireSeconds(60L);
        return new JwtTokenProvider(properties);
    }
}
